version: "3.7"
services:
#  frontend:
#    build: ./frontend
#    environment:
#      - NODE_ENV=development
#      - HOST=0.0.0.0
#      - CHOKIDAR_USEPOLLING=true
#    volumes:
#      - ./frontend:/usr/src/app
#    command: sh -c 'npm install && npm run dev'
#    ports:
#      - '3000:3000'
#    tty: true
  backend:
    build: ./backend
    tty: true
    restart: always
    volumes:
      - ./backend:/var/www/laravel
      - /var/www/laravel/storage/framework
      - /var/www/laravel/vendor
    ports:
      - '8000:8000'
  mysql:
    image: mysql:8.0
#    command: --initialize-insecure --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: 'Fh_8zrJsJJWw'
      MYSQL_DATABASE: 'scrsystem_db'
      MYSQL_USER: 'scrsystem_dbuser'
      MYSQL_PASSWORD: 'P@ssW0rd'
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
#  nginx:
#    build:
#      context: ./nginx/
#      dockerfile: Dockerfile
#    ports:
#      - 80:80
#    tty: true
#    restart: always
#    depends_on:
##      - frontend
#      - backend
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
